---
- hosts: ceph
  gather_facts: true
  become: true
  vars:
    - diskWipe: true
  roles:
    - node-wipefs

- hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars/inventory.yml
  roles:
    - local-kubectl
    - k8s-olm
    - k8s-rook-ceph
