---
- hosts: localhost
  gather_facts: false
  connection: local
  become: false
  vars_files:
    - vars/vault_hcloud_token.yml
    - vars/inventory.yml
    - vars/storage.yml
  roles:
    - hcloud-disks
