---
- hosts: k8s-cluster
  gather_facts: true
  become: true
  vars:
    packages:
      - lvm2
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"

- hosts: ceph
  gather_facts: true
  become: true
  vars:
    - diskWipe: true
    - rookHostDir: /var/lib/rook
  roles:
    - node-wipefs
  tasks:
    - name: Delete the host directory that is going to be used by this cluster
      file:
        path: "{{ rookHostDir }}"
        state: absent

- hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars/inventory.yml
  roles:
    - local-kubectl
    #- k8s-olm
    - k8s-rook-ceph

# Add everything to one role and use deletegate_to for specific targets
