---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: "{{ keycloakClusterName }}-client-{{ item }}"
  labels:
    keycloak-cluster: "{{ keycloakClusterName }}"
spec:
  realmSelector:
    matchLabels:
      keycloak-cluster: "{{ keycloakClusterName }}"
  client:
    clientId: "{{ item }}"
    secret: lookup('password', '/tmp/passwordfile length=64 chars=ascii_letters,digits,hexdigits,punctuation')
    clientAuthenticatorType: client-secret
    protocol: openid-connect
