---
- name: Create the keycloak operator
  shell: "echo '{{ lookup('template', 'templates/keycloak-operator.yml') }}' | {{ kubectl }} apply -f -"

- name: Wait for the operator to be ready
  shell: "{{ kubectl }} #do stuff here"

- name: Create the keycloak cluster
  shell: "echo '{{ lookup('template', 'templates/keycloak-cluster.yml') }}' | {{ kubectl }} apply -f -"
