- name: Delete cluster node
  hcloud_server:
    api_token: "{{ vaultHcloudToken }}"
    name: "{{ hostvars[item].ansible_host }}"
    state: absent
  loop: "{{ groups['all'] }}"

- name: Delete A record
  cloudflare_dns:
    zone: "{{ cluster.domain }}"
    record: "{{ hostvars[item].ansible_host }}"
    type: A
    account_email: "{{ vaultCloudflareEmail }}"
    account_api_token: "{{ vaultCloudflareToken }}"
    state: absent
  loop: "{{ groups['all'] }}"

- name: Delete local cluster directory
  file:
    path: "{{ playbook_dir }}/replicas-cluster-{{ cluster.domain }}"
    state: absent
