- name: Delete cluster node
  hcloud_server:
    api_token: "{{ vaultHcloudToken }}"
    name: "{{ hostvars[item].ansible_host }}"
    state: absent
  loop: "{{ groups['all'] }}"

- name: Delete volumes
  hcloud_volume:
    api_token: "{{ hcloudToken }}"
    name: "{{ item[0] }}.nodes.{{ cluster.domain }}-vol{{ item[1] }}"
    state: absent
  loop: "{{ storageNodes | product(query('sequence', 'start=1 end='+storageDisks|string)) | list }}"
  retries: 50
  delay: 3
  register: result
  until: result.rc == 0
  when: storageDisks | int > 0

- name: Delete A record
  cloudflare_dns:
    zone: "{{ cluster.domain }}"
    record: "{{ hostvars[item].ansible_host }}"
    type: A
    account_email: "{{ vaultCloudflareEmail }}"
    account_api_token: "{{ vaultCloudflareToken }}"
    state: absent
  loop: "{{ groups['all'] }}"

- name: Delete the network
  hcloud_network:
    api_token: "{{ hcloudToken }}"
    name: "{{ cluster.network }}"
    state: absent

- name: Delete local cluster directory
  file:
    path: "{{ playbook_dir }}/replicas-cluster-{{ cluster.domain }}"
    state: absent
