- name: Delete cluster node
  hcloud_server:
    api_token: "{{ vaultHcloudToken }}"
    name: "{{ hostvars[item].ansible_host }}"
    state: absent
  loop: "{{ groups['all'] }}"

- name: Delete volumes
  hcloud_volume:
    api_token: "{{ hcloudToken }}"
    name: "{{ item[0] }}.nodes.{{ cluster.domain }}-vol{{ item[1] }}"
    state: absent
  loop: "{{ storageNodes | product(query('sequence', 'start=0 end='+(storageDisks -1 )|string)) | list }}"
  when: storageDisks > 0

- name: Delete A record
  cloudflare_dns:
    zone: "{{ cluster.domain }}"
    record: "{{ hostvars[item].ansible_host }}"
    type: A
    account_email: "{{ vaultCloudflareEmail }}"
    account_api_token: "{{ vaultCloudflareToken }}"
    state: absent
  loop: "{{ groups['all'] }}"

- name: Delete local cluster directory
  file:
    path: "{{ playbook_dir }}/replicas-cluster-{{ cluster.domain }}"
    state: absent
