  # placement:
  #   all:
  #     nodeAffinity:
  #       requiredDuringSchedulingIgnoredDuringExecution:
  #         nodeSelectorTerms:
  #         - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
# {% for node in storageNodes %}
#               - "{{ node }}"
# {% endfor %}
