---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ namespace }}"

---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: "{{ namespace }}"
  spec:
    targetNamespaces:
      - "{{ namespace }}"

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "{{ operatorName }}"
  namespace: "{{ namespace }}"
  spec:
    channel: "{{ operatorChannel }}"
    name: keycloak-operator
    source: operatorhubio-catalog
    sourceNamespace: olm
