---
- name: Create and attach volumes to storage nodes
  hcloud_volume:
    api_token: "{{ hcloudToken }}"
    name: "{{ item[0] }}.nodes.{{ cluster.name }}.{{ cluster.domain }}-vol{{ item[1] }}"
    server: "{{ item[0] }}.nodes.{{ cluster.name }}.{{ cluster.domain }}"
    automount: yes
    format: xfs
    size: "{{ storageDiskSizeGB }}"
    state: present
  loop: "{{ storageNodes | product(query('sequence', 'start=1 end='+storageDisks|string)) | list }}"
  when: storageDisks | int > 0
